typeset -g POWERLEVEL9K_MODE="nerdfont-complete"

typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    vcs
    dir_writable
    dir
    anaconda
    virtualenv
    newline
    context
    prompt_char
)
typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    status
    background_jobs
    command_execution_time
    time
    newline
)

typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX="\u250f "
typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX="\u2517 "

typeset -g POWERLEVEL9K_BACKGROUND=
typeset -g POWERLEVEL9K_{LEFT,RIGHT}_{LEFT,RIGHT}_WHITESPACE=
typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SUBSEGMENT_SEPARATOR=" "
typeset -g POWERLEVEL9K_{LEFT,RIGHT}_SEGMENT_SEPARATOR=

typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND="white"
typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND="red"

typeset -g POWERLEVEL9K_CONTEXT_{,REMOTE_}TEMPLATE="%m"
typeset -g POWERLEVEL9K_CONTEXT_{,REMOTE_}FOREGROUND="cyan"
typeset -g POWERLEVEL9K_CONTEXT_{ROOT,REMOTE_SUDO}_TEMPLATE="%B%n@%m"
typeset -g POWERLEVEL9K_CONTEXT_{ROOT,REMOTE_SUDO}_FOREGROUND="red"

typeset -g POWERLEVEL9K_ANACONDA_{LEFT,RIGHT}_DELIMITER=
typeset -g POWERLEVEL9K_ANACONDA_FOREGROUND="009"

typeset -g POWERLEVEL9K_VIRTUALENV_{LEFT,RIGHT}_DELIMITER=
typeset -g POWERLEVEL9K_VIRTUALENV_FOREGROUND="005"

typeset -g POWERLEVEL9K_VCS_CLEAN_FOREGROUND="green"
typeset -g POWERLEVEL9K_VCS_MODIFIED_FOREGROUND="yellow"
typeset -g POWERLEVEL9K_VCS_UNTRACKED_FOREGROUND="yellow"

typeset -g POWERLEVEL9K_SHORTEN_STRATEGY="truncate_to_unique"
typeset -g POWERLEVEL9K_DIR_MAX_LENGTH=""
typeset -g POWERLEVEL9K_DIR_DEFAULT_FOREGROUND="105"
typeset -g POWERLEVEL9K_DIR_HOME_FOREGROUND="075"
typeset -g POWERLEVEL9K_DIR_HOME_SUBFOLDER_FOREGROUND="075"
typeset -g POWERLEVEL9K_DIR_WRITABLE_FORBIDDEN_FOREGROUND="red"

typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND="green"
typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND="red"

typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT="d h m s"
typeset -g POWERLEVEL9K_TIME_FOREGROUND="cyan"

typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND="magenta"

typeset -g POWERLEVEL9K_BACKGROUND_JOBS_FOREGROUND="152"

typeset -g GITSTATUS_NUM_THREADS=1
